### PR TITLE
Fix discrepancies between JS and Native implementations

### LINKED ISSUE #5: Add strict flag to verify in JS impl
Presently the `strict` flag is only supported by the native version

### PR DESCRIPTION
**Pull request by junderw**
Fixes #5 

@yuki-js Please review.

### CODE REVIEW

**Comment by junderw** [comment]
I tested the native implementation manually for acceptable values.

Native impl accepted truthy values ( 0, '', etc. were false, 57, 'abc', etc. were true) So the js impl will match that and allow truthy values and not perform strict type checks on the `strict` parameter.

**Comment by yuki-js** [comment]
C++ implementation normalizes if strict. 
https://github.com/bitcoinjs/tiny-secp256k1/blob/9f07a89d5d9838628e34ac76db9ce64d9d1d3372/native/addon.cpp#L343

**Comment by junderw** [comment]
> C++ implementation normalizes if strict.
> https://github.com/bitcoinjs/tiny-secp256k1/blob/9f07a89d5d9838628e34ac76db9ce64d9d1d3372/native/addon.cpp#L343

No. It normalizes if NOT strict.

The reason why is because the C library we call is ALWAYS strict (will return false if S value is high).

The normalization function just makes sure the s value is low.

- CPP: If not strict. We will fix the S value for you, because the library is always stict.
- JS: Our verify function is not strict, so if strict, we return false when high S (to make it strict).

It's very hard to understand..... even for me.

**Comment by yuki-js** [comment]
Oh, I made a mistake. " if NOT correct" is correct.

File: native/addon.cpp [hunk 1]
```diff
@@ -77,8 +77,9 @@ namespace {
 
 	template <size_t index, typename I, typename A>
 	unsigned int assumeCompression (const I& info, const A& p) {
-		if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
-		if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
+		if (info.Length() <= index || info[index]->IsUndefined()) {
+			return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
+		}
```
Comment (junderw) [inline native/addon.cpp:82]: Current behavior when uncompressed key is passed in:

||native|JS|
|---|---|---|
|no compressed arg (implicit undefined)|UC|UC|
|pass undefined to compressed arg|C|UC|

This solution changes it to 

||native|JS|
|---|---|---|
|no compressed arg (implicit undefined)|UC|UC|
|pass undefined to compressed arg|UC|UC|

Also note that explicitly passing falsey values like 0, '', null, and others, will be treated the same as `false`

Comment (junderw) [reply native/addon.cpp:82]: Note that this discrepancy in JS and Native exists by the nature of assumeCompression not having access to all the arguments of the calling function...

Another way to remove the discrepancy would be to pass `arguments` as an arg to assumeCompression similar to the Native code...

Perhaps JS should adhere to Native here... but I feel like the JS logic makes more sense. "If undefined, follow the key's compressed attribute" should be the same regardless of implicit undefined (no arg) and explicit undefined.

Comment (junderw) [reply native/addon.cpp:82]: Which is why I solved it this way.

Comment (junderw) [reply native/addon.cpp:82]: Since the only people affected by this change would be people who pass in an uncompressed pubkey along with explicitly passing undefined for compressed. (Though notably, that could also be people who wanted to pass true but misspelled the object parameter. If they were using native they wouldn't have noticed their typo thanks to our behavior)

Comment (junderw) [reply native/addon.cpp:82]: I don't think a major semver bump is needed.
